### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by pwalter-ebi** [visual-framework/vf-covid19-boilerplate#27]
```
[08:29:47] 'vf-lint:js-soft-fail' errored after 78 ms
[08:29:47] Error: No ESLint configuration found in .../vf-covid19-boilerplate/src/components/vf-core-components/vf-banner.
    at CascadingConfigArrayFactory._finalizeConfigArray (.../vf-covid19-boilerplate/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:432:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (.../vf-covid19-boilerplate/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at CLIEngine.isPathIgnored (.../vf-covid19-boilerplate/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cli-engine.js:951:18)
    at Transform._transform (.../vf-covid19-boilerplate/node_modules/gulp-eslint/index.js:43:14)
    at Transform._read (_stream_transform.js:189:10)
    at Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at Transform.Writable.write (_stream_writable.js:302:11)
    at DestroyableTransform.ondata (.../vf-covid19-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:619:20)
[08:29:47] 'vf-scripts' errored after 2.02 s
[08:29:47] 'build' errored after 2.04 s
error Command failed with exit code 1.

```

**Comment by khawkins98** [comment]
This is probably because of the new component updates. A `yarn install` should fix it.

Or, the 💥  option: `rm -rf node_modules yarn.lock && yarn instal`

**Comment by khawkins98** [comment]
Actually saw this on my local, investigating and doing `rm -rf node_modules yarn.lock && yarn instal`

**Comment by pwalter-ebi** [comment]
Same error after 💥

**Comment by khawkins98** [comment]
Now fixed in the above commit:

> In the latest minor release vf-core now expects to find a lint file, this is a bug and should be optional.
>
> Will make a fix for vf-core later, however this patch adds the linter config and gets things working.
